on:
  workflow_dispatch: {}

name: Publish

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Validate rules
        run: |
          semgrep validate rules/ || {
            echo "semgrep validate failed. Configuration is invalid."
            exit 1
          }

      - name: Run Semgrep CI rule check
        run: |
          semgrep --error --config "p/semgrep-rule-ci"

      - name: Run semgrep publish
        run: |
          semgrep publish rules/

      - name: Add rules to policy
        run: |
          python3 scripts/put_rules_in_mode.py
          
